In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, BatchNormalization
from tensorflow.keras.layers import Conv2D, MaxPooling2D, AveragePooling2D, GlobalAveragePooling2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import LearningRateScheduler
from tensorflow.keras.layers import Add,concatenate
from tensorflow.keras.layers import Input
from tensorflow.keras import Model
from sklearn.model_selection import train_test_split

In [3]:
#from google.colab import files
#uploaded = files.upload()
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [4]:
cd 'drive/My Drive/ECE 657/Part-2/'

/content/drive/My Drive/ECE 657/Part-2


In [5]:
train = pd.read_csv('train.csv')
test = pd.read_csv('testX.csv')
train.describe()

Id         Label  ...           783           784
count  60000.000000  60000.000000  ...  60000.000000  60000.000000
mean   39999.500000      2.002933  ...      0.832950      0.072850
std    17320.652413      1.415000  ...      9.263115      2.131444
min    10000.000000      0.000000  ...      0.000000      0.000000
25%    24999.750000      1.000000  ...      0.000000      0.000000
50%    39999.500000      2.000000  ...      0.000000      0.000000
75%    54999.250000      3.000000  ...      0.000000      0.000000
max    69999.000000      4.000000  ...    255.000000    170.000000

[8 rows x 786 columns]

In [6]:
train['Label'].unique()

array([4, 0, 1, 2, 3])

In [7]:
batch_size = 1024
num_classes = 5
epochs = 300
img_rows, img_cols = 28, 28

x_train = train.drop(['Label', 'Id'], axis=1).to_numpy()
y_train = train['Label'].to_numpy()
x_test = test.drop(['Id'], axis = 1).to_numpy()

x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size = 0.1, random_state = 42)
x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_val = x_val.reshape(x_val.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

y_train = tensorflow.keras.utils.to_categorical(y_train, num_classes)
y_val = tensorflow.keras.utils.to_categorical(y_val, num_classes)

print(x_val.shape)
print(y_val)

x_train = x_train.astype('float32')
x_val = x_val.astype('float32')

x_train /= 255
x_val /= 255

(6000, 28, 28, 1)
[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [0]:
#DenseNet
model = Sequential()
model.add(Flatten())
model.add(Dense(1024, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss = 'categorical_crossentropy', optimizer = Adam(0.0008), metrics = ['accuracy'])

In [11]:
history = model.fit(x_train, y_train,
          batch_size = batch_size,
          epochs = epochs,
          verbose = 1,
          validation_data = (x_val, y_val))

model.summary()

Epoch 1/300
53/53 [==============================] - 0s 6ms/step - loss: 0.4895 - accuracy: 0.7924 - val_loss: 0.4536 - val_accuracy: 0.8073
Epoch 2/300
53/53 [==============================] - 0s 7ms/step - loss: 0.4665 - accuracy: 0.8041 - val_loss: 0.4365 - val_accuracy: 0.8283
Epoch 3/300
53/53 [==============================] - 0s 6ms/step - loss: 0.4415 - accuracy: 0.8165 - val_loss: 0.4197 - val_accuracy: 0.8288
Epoch 4/300
53/53 [==============================] - 0s 6ms/step - loss: 0.4187 - accuracy: 0.8255 - val_loss: 0.4117 - val_accuracy: 0.8307
Epoch 5/300
53/53 [==============================] - 0s 6ms/step - loss: 0.4082 - accuracy: 0.8297 - val_loss: 0.4367 - val_accuracy: 0.8217
Epoch 6/300
53/53 [==============================] - 0s 6ms/step - loss: 0.3911 - accuracy: 0.8386 - val_loss: 0.4884 - val_accuracy: 0.7960
Epoch 7/300
53/53 [==============================] - 0s 6ms/step - loss: 0.3780 - accuracy: 0.8445 - val_loss: 0.4021 - val_accuracy: 0.8390
Epoch 8/300
5

In [12]:
import time
start = time.time()
score = model.evaluate(x_val, y_val, verbose = 0)
end = time.time()
print(end-start)

0.40610218048095703


In [13]:
from sklearn.datasets import make_circles
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix

# predict probabilities for test set
yhat_probs = model.predict(x_val, verbose=0)

yhat_classes = yhat_probs.argmax(axis=-1)

# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(y_val.argmax(axis=-1), yhat_classes)
print('Accuracy: %f' % accuracy)

# precision tp / (tp + fp)
precision = precision_score(y_val.argmax(axis=-1), yhat_classes, average = 'micro')
print('Precision: %f' % precision)

# recall: tp / (tp + fn)
recall = recall_score(y_val.argmax(axis=-1), yhat_classes, average = 'micro')
print('Recall: %f' % recall)

# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(y_val.argmax(axis=-1), yhat_classes, average = 'micro')
print('F1 score: %f' % f1)
 
# kappa
kappa = cohen_kappa_score(y_val.argmax(axis=-1), yhat_classes)
print('Cohens kappa: %f' % kappa)

# ROC AUC
auc = roc_auc_score(y_val, yhat_probs)
print('ROC AUC: %f' % auc)

matrix = multilabel_confusion_matrix(y_val.argmax(axis=-1), yhat_classes, labels = [0,1,2,3,4])
print(matrix)

#Reference:
#https://datascience.stackexchange.com/questions/15989/micro-average-vs-macro-average-performance-in-a-multiclass-classification-settin

Accuracy: 0.872167
Precision: 0.872167
Recall: 0.872167
F1 score: 0.872167
Cohens kappa: 0.840203
ROC AUC: 0.982407
[[[4724   86]
  [  57 1133]]

 [[4604  166]
  [ 172 1058]]

 [[4581  237]
  [ 192  990]]

 [[4632  193]
  [ 221  954]]

 [[4692   85]
  [ 125 1098]]]


In [15]:
x_test = test.drop(['Id'], axis = 1).to_numpy()
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
x_test = x_test.astype('float32')
x_test /= 255
y_sol = model.predict(x_test)
y_sol = y_sol.argmax(axis=-1)
y_sol

array([3, 4, 1, ..., 3, 2, 2])

In [0]:
df_solution = pd.DataFrame(np.arange(0, x_test.shape[0]), columns=['Id'])
df_solution['Label'] = y_sol

In [17]:
df_solution

Id  Label
0        0      3
1        1      4
2        2      1
3        3      1
4        4      1
...    ...    ...
9995  9995      1
9996  9996      1
9997  9997      3
9998  9998      2
9999  9999      2

[10000 rows x 2 columns]